apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db-service
spec:
  ports:
    - port: {{ .Values.mongodb.servicePort }}
      targetPort: {{ .Values.mongodb.servicePort }}
  selector:
    app: {{ .Release.Name }}-db
